package iscsi

import (
	"bytes"
	"context"
	"log/slog"
	"strings"
	"sync"
	"testing"

	"github.com/piwi3910/truenas-csi/internal/backend"
	"github.com/piwi3910/truenas-csi/internal/obs"
)

func testParams(t *testing.T, over map[string]string) Params {
	t.Helper()
	m := map[string]string{}
	for k, v := range over {
		m[k] = v
	}
	p, err := parseParams("Pool0", "k8s", m)
	if err != nil {
		t.Fatalf("parseParams(%v): %v", m, err)
	}
	return p
}

// TestEnsureTargetIsIdempotent covers the retry the sidecars guarantee will
// happen: two CreateVolume calls racing on a cold backend must converge on ONE
// target. A second target with the same name is rejected by the appliance, so
// a lost race surfaces as a failed provision rather than as duplicate state.
func TestEnsureTargetIsIdempotent(t *testing.T) {
	n := newNAS(t)
	c := n.client()
	p := testParams(t, map[string]string{"chap": "false", "initiatorACL": "false"})

	var (
		wg  sync.WaitGroup
		mu  sync.Mutex
		ids []int
		iqn string
	)
	errs := make(chan error, 2)
	for i := 0; i < 2; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			id, gotIQN, err := ensureTarget(context.Background(), c, p)
			if err != nil {
				errs <- err
				return
			}
			mu.Lock()
			ids = append(ids, id)
			iqn = gotIQN
			mu.Unlock()
		}()
	}
	wg.Wait()
	close(errs)
	for err := range errs {
		t.Fatalf("ensureTarget: %v", err)
	}

	if got := n.s.CallsTo("iscsi.target.create"); got != 1 {
		t.Fatalf("want exactly one iscsi.target.create, got %d", got)
	}
	if len(ids) != 2 || ids[0] != ids[1] {
		t.Fatalf("both callers must see the same target id, got %v", ids)
	}
	if want := "iqn.2005-10.org.freenas.ctl:" + targetName("Pool0", "k8s"); iqn != want {
		t.Fatalf("iqn: want %q, got %q", want, iqn)
	}

	// A third call on a warm backend must not create anything either.
	if _, _, err := ensureTarget(context.Background(), c, p); err != nil {
		t.Fatalf("third ensureTarget: %v", err)
	}
	if got := n.s.CallsTo("iscsi.target.create"); got != 1 {
		t.Fatalf("a warm backend must not create again, got %d creates", got)
	}
}

// TestEnsurePortalRespectsOverride: an operator who names an existing portal is
// telling the driver the network layout is already configured. Creating a
// portal anyway would bind a second listener the operator did not ask for.
func TestEnsurePortalRespectsOverride(t *testing.T) {
	n := newNAS(t)
	c := n.client()

	p := testParams(t, map[string]string{"portalID": "4", "chap": "false", "initiatorACL": "false"})
	id, err := ensurePortal(context.Background(), c, p)
	if err != nil {
		t.Fatalf("ensurePortal: %v", err)
	}
	if id != 4 {
		t.Fatalf("want the operator's portal 4, got %d", id)
	}
	if got := n.s.CallsTo("iscsi.portal.create"); got != 0 {
		t.Fatalf("portalID must suppress creation entirely, got %d creates", got)
	}

	// Without the override the driver provides one, exactly once.
	auto := testParams(t, map[string]string{"chap": "false", "initiatorACL": "false"})
	first, err := ensurePortal(context.Background(), c, auto)
	if err != nil {
		t.Fatalf("ensurePortal: %v", err)
	}
	second, err := ensurePortal(context.Background(), c, auto)
	if err != nil {
		t.Fatalf("ensurePortal: %v", err)
	}
	if first != second {
		t.Fatalf("the driver's own portal must be reused: %d then %d", first, second)
	}
	if got := n.s.CallsTo("iscsi.portal.create"); got != 1 {
		t.Fatalf("want one portal create, got %d", got)
	}
}

// TestCHAPGeneratedPerTarget: CHAP is on by default, its secret is generated by
// the driver, and it must never reach the log. A secret in a log line is a
// permanent leak into whatever aggregates the cluster's logs.
func TestCHAPGeneratedPerTarget(t *testing.T) {
	n := newNAS(t)
	c := n.client()

	var buf bytes.Buffer
	obs.SetLogOutput(&buf, slog.LevelDebug)
	t.Cleanup(func() { obs.SetLogOutput(nil, slog.LevelInfo) })

	p := testParams(t, map[string]string{"initiatorACL": "false"})
	if !p.CHAP {
		t.Fatal("CHAP must default to on")
	}
	if _, _, err := ensureTarget(context.Background(), c, p); err != nil {
		t.Fatalf("ensureTarget: %v", err)
	}

	secrets := n.authSecrets()
	if len(secrets) != 1 {
		t.Fatalf("want exactly one iscsi.auth entry, got %d", len(secrets))
	}
	secret := secrets[0]
	if len(secret) < 12 {
		t.Fatalf("CHAP secret must be at least 12 characters, got %d", len(secret))
	}

	// A second ensure must reuse the credential, not mint a new one.
	if _, _, err := ensureTarget(context.Background(), c, p); err != nil {
		t.Fatalf("second ensureTarget: %v", err)
	}
	if got := n.s.CallsTo("iscsi.auth.create"); got != 1 {
		t.Fatalf("want one iscsi.auth.create, got %d", got)
	}

	// The publish context carries the credential to the node...
	ctx := context.Background()
	if _, err := n.backendWith(c).Create(ctx, createReq("pvc-chap", 1<<30, map[string]string{"initiatorACL": "false"})); err != nil {
		t.Fatalf("Create: %v", err)
	}
	pc, err := n.backendWith(c).Publish(ctx, volID("pvc-chap"),
		backend.NodeRef{ID: "worker-1", Addrs: []string{"10.0.0.1"}})
	if err != nil {
		t.Fatalf("Publish: %v", err)
	}
	if pc["chapUser"] == "" || pc["chapSecret"] != secret {
		t.Fatalf("publish context must carry the CHAP credential, got %v", redactedKeys(pc))
	}

	// ...but nothing may carry it into the log.
	if strings.Contains(buf.String(), secret) {
		t.Fatalf("the CHAP secret leaked into log output")
	}
}

func redactedKeys(m map[string]string) []string {
	out := []string{}
	for k := range m {
		out = append(out, k)
	}
	return out
}

// TestInitiatorACLRestrictsToNodes: the shared target exposes every LUN to
// every logged-in initiator, so the initiator group is the only thing keeping
// machines outside the cluster off it.
func TestInitiatorACLRestrictsToNodes(t *testing.T) {
	iqns := []string{"iqn.2004-10.com.ubuntu:01:node21", "iqn.2004-10.com.ubuntu:01:node22"}

	n := newNAS(t)
	c := n.client()
	p := testParams(t, map[string]string{
		"chap":     "false",
		"nodeIQNs": strings.Join(iqns, ","),
	})
	if _, _, err := ensureTarget(context.Background(), c, p); err != nil {
		t.Fatalf("ensureTarget: %v", err)
	}
	got := n.initiators()
	if len(got) != len(iqns) {
		t.Fatalf("initiator group must list the cluster nodes, got %v", got)
	}
	for _, want := range iqns {
		found := false
		for _, g := range got {
			if g == want {
				found = true
			}
		}
		if !found {
			t.Fatalf("initiator group is missing %q, got %v", want, got)
		}
	}

	// Opting out must create no group at all — an empty group would deny
	// everything rather than allow everything.
	n2 := newNAS(t)
	c2 := n2.client()
	off := testParams(t, map[string]string{"chap": "false", "initiatorACL": "false", "nodeIQNs": strings.Join(iqns, ",")})
	if _, _, err := ensureTarget(context.Background(), c2, off); err != nil {
		t.Fatalf("ensureTarget: %v", err)
	}
	if got := n2.initiatorGroups(); got != 0 {
		t.Fatalf("initiatorACL=false must create no initiator group, got %d", got)
	}
}

// TestPortalAddressRejectsWildcard pins a bug found against a real cluster: a
// portal listening on 0.0.0.0 reported that address in the publish context, and
// the initiator answered "cannot make connection to 0.0.0.0: Connection
// refused". The wildcard is where the appliance listens, not somewhere a node
// can dial.
func TestPortalAddressRejectsWildcard(t *testing.T) {
	for _, ip := range []string{"0.0.0.0", "::", "[::]", "*", " "} {
		if !isWildcardAddress(ip) {
			t.Errorf("%q must be treated as a wildcard listen address", ip)
		}
	}
	for _, ip := range []string{"192.168.10.253", "10.0.0.1", "fd00::1"} {
		if isWildcardAddress(ip) {
			t.Errorf("%q is a real address and must be used as-is", ip)
		}
	}
}

// TestFindAuthRefusesARedactedSecret pins the fix for the worst failure this
// driver had: a volume that provisions cleanly and then cannot be attached
// anywhere.
//
// TrueNAS does not refuse iscsi.auth.query for an account that may not read
// secrets — it answers, with the secret replaced by asterisks. The driver put
// that in the publish context, the node logged in with it, and every attach
// failed with "iSCSI login failed due to authorization failure" on the node, at
// pod start, with nothing wrong in the controller's logs. Reproduced on 25.10.6
// with an account holding exactly the roles docs/security.md used to list.
func TestFindAuthRefusesARedactedSecret(t *testing.T) {
	n := newNAS(t)
	n.s.HandleValue("iscsi.auth.query", []any{map[string]any{
		"id": 1, "tag": 1, "user": "csi-pool0-k8s", "secret": "********",
	}})
	c := n.client()

	_, err := findAuth(context.Background(), c, "csi-pool0-k8s")
	if err == nil {
		t.Fatal("a redacted CHAP secret was accepted; the node would be handed " +
			"asterisks and every iSCSI attach would fail")
	}
	if !strings.Contains(err.Error(), "SHARING_ISCSI_AUTH_WRITE") {
		t.Errorf("the error must name the role that fixes it, got: %v", err)
	}
}

// TestFindAuthAcceptsARealSecret is the other half: the guard must not reject a
// legitimate secret, including one an operator set by hand.
func TestFindAuthAcceptsARealSecret(t *testing.T) {
	n := newNAS(t)
	n.s.HandleValue("iscsi.auth.query", []any{map[string]any{
		"id": 1, "tag": 1, "user": "csi-pool0-k8s", "secret": "5Hf7EAEfYPFa8Wqf",
	}})
	c := n.client()

	got, err := findAuth(context.Background(), c, "csi-pool0-k8s")
	if err != nil {
		t.Fatalf("findAuth: %v", err)
	}
	if got == nil || got.Secret != "5Hf7EAEfYPFa8Wqf" {
		t.Errorf("findAuth returned %+v, want the real secret", got)
	}
}
