package truenas

import (
	"context"
	"encoding/json"
	"strconv"
)

// NVMe-oF (nvmet) surface.
//
// Every method here mirrors a call proven against a live TrueNAS 25.10.6:
// nvmet.subsys.create returns both the subsystem NQN and an auto-generated
// serial, nvmet.namespace.create binds a zvol to a subsystem, and a port plus a
// port_subsys binding is what actually exports it.
//
// Two decoding notes, both defensive rather than cosmetic:
//   - reference fields (subsys_id, port_id, host_id) come back as a plain id on
//     some endpoints and as a nested object on others depending on the query
//     options, so they are decoded through refField;
//   - addr_trsvcid is a port number the middleware has been seen to render both
//     as a number and as a string, so it is decoded through flexInt.
//
// Getting either wrong would not fail loudly — it would silently yield a zero
// id, and the driver would then bind a namespace to subsystem 0.

// refField decodes a reference that is either an id or an object carrying one.
type refField struct{ ID int }

func (r *refField) UnmarshalJSON(b []byte) error {
	var n int
	if err := json.Unmarshal(b, &n); err == nil {
		r.ID = n
		return nil
	}
	var obj struct {
		ID int `json:"id"`
	}
	if err := json.Unmarshal(b, &obj); err == nil {
		r.ID = obj.ID
	}
	return nil
}

// flexInt decodes an integer rendered as a number or as a string.
type flexInt int

func (f *flexInt) UnmarshalJSON(b []byte) error {
	var n int
	if err := json.Unmarshal(b, &n); err == nil {
		*f = flexInt(n)
		return nil
	}
	var s string
	if err := json.Unmarshal(b, &s); err == nil {
		if v, err := strconv.Atoi(s); err == nil {
			*f = flexInt(v)
		}
	}
	return nil
}

// NVMeGlobal is the appliance-wide NVMe-oF configuration.
type NVMeGlobal struct {
	// BaseNQN prefixes every subsystem NQN: <basenqn>:<subsystem name>.
	BaseNQN string `json:"basenqn"`
	Kernel  bool   `json:"kernel"`
	ANA     bool   `json:"ana"`
	// RDMA reports whether the appliance can serve NVMe over RDMA at all. The
	// validation appliance reports false.
	RDMA bool `json:"rdma"`
}

// NVMeSubsystem is one nvmet subsystem.
type NVMeSubsystem struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	// SubNQN is what an initiator connects to.
	SubNQN string `json:"subnqn"`
	// Serial is generated by the appliance and is the node's only stable key
	// for the resulting block device (/dev/disk/by-id/nvme-<model>_<serial>).
	Serial       string `json:"serial"`
	AllowAnyHost bool   `json:"allow_any_host"`
}

// NVMeNamespace is a zvol exported inside a subsystem.
type NVMeNamespace struct {
	ID         int      `json:"id"`
	SubsysID   refField `json:"subsys_id"`
	DeviceType string   `json:"device_type"`
	DevicePath string   `json:"device_path"`

	// Enabled is the namespace's own switch. A POINTER because absent must not
	// read as disabled: middleware that stopped reporting the field would
	// otherwise make every namespace look dead and refuse every publish.
	Enabled *bool `json:"enabled"`
}

// Serving reports whether the appliance is actually presenting this namespace.
// A namespace that does not report the field is assumed to be.
func (n *NVMeNamespace) Serving() bool { return n == nil || n.Enabled == nil || *n.Enabled }

// NVMePort is a transport endpoint subsystems are bound to.
type NVMePort struct {
	ID      int     `json:"id"`
	TRType  string  `json:"addr_trtype"`
	TRAddr  string  `json:"addr_traddr"`
	TRSvcID flexInt `json:"addr_trsvcid"`

	// Enabled is the listener's own switch. A POINTER because absent must not
	// read as disabled: middleware that does not report the field at all would
	// otherwise make every port look unusable and stop provisioning outright.
	Enabled *bool `json:"enabled"`
}

// Listening reports whether the port is actually serving. A port that does not
// report the field is assumed to be, which is how every release before it
// behaved.
func (p *NVMePort) Listening() bool { return p == nil || p.Enabled == nil || *p.Enabled }

// Port returns the port's service id as an int.
func (p *NVMePort) Port() int { return int(p.TRSvcID) }

// NVMePortSubsys binds a subsystem to a port.
type NVMePortSubsys struct {
	ID       int      `json:"id"`
	PortID   refField `json:"port_id"`
	SubsysID refField `json:"subsys_id"`
}

// NVMeHost is a registered initiator NQN — the NVMe equivalent of an iSCSI
// initiator group entry.
type NVMeHost struct {
	ID      int    `json:"id"`
	HostNQN string `json:"hostnqn"`
}

// NVMeHostSubsys binds a host to a subsystem.
type NVMeHostSubsys struct {
	ID       int      `json:"id"`
	HostID   refField `json:"host_id"`
	SubsysID refField `json:"subsys_id"`
}

// NVMeGlobalConfig returns the appliance-wide NVMe-oF configuration.
func (c *Ops) NVMeGlobalConfig(ctx context.Context) (*NVMeGlobal, error) {
	var g NVMeGlobal
	if err := c.CallJSON(ctx, &g, "nvmet.global.config"); err != nil {
		return nil, err
	}
	return &g, nil
}

// NVMeSubsysByName finds a subsystem, or (nil, nil) when absent.
func (c *Ops) NVMeSubsysByName(ctx context.Context, name string) (*NVMeSubsystem, error) {
	var out []NVMeSubsystem
	err := c.CallJSON(ctx, &out, "nvmet.subsys.query",
		[]any{[]any{"name", "=", name}}, map[string]any{})
	if err != nil {
		if IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	if len(out) == 0 {
		return nil, nil
	}
	return &out[0], nil
}

// NVMeSubsysCreate creates a subsystem. allowAnyHost true leaves it open to any
// initiator; false means the caller MUST bind at least one host to it, because
// a closed subsystem with an empty host list accepts nobody.
func (c *Ops) NVMeSubsysCreate(ctx context.Context, name string, allowAnyHost bool) (*NVMeSubsystem, error) {
	var s NVMeSubsystem
	if err := c.CallJSON(ctx, &s, "nvmet.subsys.create", map[string]any{
		"name": name, "allow_any_host": allowAnyHost,
	}); err != nil {
		return nil, err
	}
	return &s, nil
}

// NVMeSubsysDelete removes a subsystem. An absent subsystem is success.
func (c *Ops) NVMeSubsysDelete(ctx context.Context, id int) error {
	err := c.CallJSON(ctx, nil, "nvmet.subsys.delete", id)
	if err != nil && IsNotFound(err) {
		return nil
	}
	return err
}

// NVMeNamespaceByDevice finds the namespace exporting a zvol, or (nil, nil).
//
// The lookup is by device path rather than by subsystem id on purpose: the
// device path is the volume's identity, and it stays meaningful even when a
// previous attempt left a namespace attached to a subsystem that is gone.
func (c *Ops) NVMeNamespaceByDevice(ctx context.Context, devicePath string) (*NVMeNamespace, error) {
	var out []NVMeNamespace
	err := c.CallJSON(ctx, &out, "nvmet.namespace.query",
		[]any{[]any{"device_path", "=", devicePath}}, map[string]any{})
	if err != nil {
		if IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	if len(out) == 0 {
		return nil, nil
	}
	return &out[0], nil
}

// NVMeNamespaceCreate exports a zvol as a namespace of a subsystem. devicePath
// is the middleware's "zvol/<dataset>" form, as verified live.
func (c *Ops) NVMeNamespaceCreate(ctx context.Context, subsysID int, devicePath string) (*NVMeNamespace, error) {
	var ns NVMeNamespace
	if err := c.CallJSON(ctx, &ns, "nvmet.namespace.create", map[string]any{
		"subsys_id": subsysID, "device_type": "ZVOL", "device_path": devicePath,
	}); err != nil {
		return nil, err
	}
	return &ns, nil
}

// NVMeNamespaceDelete removes a namespace. An absent namespace is success.
func (c *Ops) NVMeNamespaceDelete(ctx context.Context, id int) error {
	err := c.CallJSON(ctx, nil, "nvmet.namespace.delete", id)
	if err != nil && IsNotFound(err) {
		return nil
	}
	return err
}

// NVMePortFind returns the port listening on this transport, address and service
// id, or (nil, nil) when there is none.
func (c *Ops) NVMePortFind(ctx context.Context, trtype, addr string, port int) (*NVMePort, error) {
	ports, err := c.NVMePortList(ctx)
	if err != nil {
		return nil, err
	}
	for i := range ports {
		p := &ports[i]
		if p.TRType == trtype && p.TRAddr == addr && p.Port() == port {
			return p, nil
		}
	}
	return nil, nil
}

// NVMePortList returns every configured port.
func (c *Ops) NVMePortList(ctx context.Context) ([]NVMePort, error) {
	var out []NVMePort
	if err := c.CallJSON(ctx, &out, "nvmet.port.query"); err != nil {
		if IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return out, nil
}

// NVMePortCreate adds a port. trtype is the middleware's spelling: TCP or RDMA.
func (c *Ops) NVMePortCreate(ctx context.Context, trtype, addr string, port int) (*NVMePort, error) {
	var p NVMePort
	if err := c.CallJSON(ctx, &p, "nvmet.port.create", map[string]any{
		"addr_trtype": trtype, "addr_traddr": addr, "addr_trsvcid": port,
	}); err != nil {
		return nil, err
	}
	return &p, nil
}

// NVMePortDelete removes a port. An absent port is success.
func (c *Ops) NVMePortDelete(ctx context.Context, id int) error {
	err := c.CallJSON(ctx, nil, "nvmet.port.delete", id)
	if err != nil && IsNotFound(err) {
		return nil
	}
	return err
}

// NVMePortSubsysList returns the port bindings of one subsystem.
func (c *Ops) NVMePortSubsysList(ctx context.Context, subsysID int) ([]NVMePortSubsys, error) {
	var out []NVMePortSubsys
	err := c.CallJSON(ctx, &out, "nvmet.port_subsys.query",
		[]any{[]any{"subsys_id", "=", subsysID}}, map[string]any{})
	if err != nil {
		if IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return out, nil
}

// NVMePortSubsysCreate binds a subsystem to a port.
func (c *Ops) NVMePortSubsysCreate(ctx context.Context, portID, subsysID int) (*NVMePortSubsys, error) {
	var ps NVMePortSubsys
	if err := c.CallJSON(ctx, &ps, "nvmet.port_subsys.create", map[string]any{
		"port_id": portID, "subsys_id": subsysID,
	}); err != nil {
		return nil, err
	}
	return &ps, nil
}

// NVMePortSubsysDelete removes a port binding. An absent binding is success.
func (c *Ops) NVMePortSubsysDelete(ctx context.Context, id int) error {
	err := c.CallJSON(ctx, nil, "nvmet.port_subsys.delete", id)
	if err != nil && IsNotFound(err) {
		return nil
	}
	return err
}

// NVMeHostByNQN finds a registered host, or (nil, nil) when absent.
func (c *Ops) NVMeHostByNQN(ctx context.Context, nqn string) (*NVMeHost, error) {
	var out []NVMeHost
	err := c.CallJSON(ctx, &out, "nvmet.host.query",
		[]any{[]any{"hostnqn", "=", nqn}}, map[string]any{})
	if err != nil {
		if IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	if len(out) == 0 {
		return nil, nil
	}
	return &out[0], nil
}

// NVMeHostCreate registers an initiator NQN.
func (c *Ops) NVMeHostCreate(ctx context.Context, nqn string) (*NVMeHost, error) {
	var h NVMeHost
	if err := c.CallJSON(ctx, &h, "nvmet.host.create", map[string]any{"hostnqn": nqn}); err != nil {
		return nil, err
	}
	return &h, nil
}

// NVMeHostSubsysList returns the host bindings of one subsystem.
func (c *Ops) NVMeHostSubsysList(ctx context.Context, subsysID int) ([]NVMeHostSubsys, error) {
	var out []NVMeHostSubsys
	err := c.CallJSON(ctx, &out, "nvmet.host_subsys.query",
		[]any{[]any{"subsys_id", "=", subsysID}}, map[string]any{})
	if err != nil {
		if IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return out, nil
}

// NVMeHostSubsysCreate grants a host access to a subsystem.
func (c *Ops) NVMeHostSubsysCreate(ctx context.Context, hostID, subsysID int) (*NVMeHostSubsys, error) {
	var hs NVMeHostSubsys
	if err := c.CallJSON(ctx, &hs, "nvmet.host_subsys.create", map[string]any{
		"host_id": hostID, "subsys_id": subsysID,
	}); err != nil {
		return nil, err
	}
	return &hs, nil
}

// NVMeHostSubsysDelete revokes a host's access. An absent binding is success.
func (c *Ops) NVMeHostSubsysDelete(ctx context.Context, id int) error {
	err := c.CallJSON(ctx, nil, "nvmet.host_subsys.delete", id)
	if err != nil && IsNotFound(err) {
		return nil
	}
	return err
}
